// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function CloseAllBrowser():Promise<void>;

export function CloseBrowser():Promise<void>;

export function OpenBrowser():Promise<void>;

export function SetConfig(arg1:config.Config):Promise<void>;
