// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseAllBrowser() {
  return window['go']['main']['App']['CloseAllBrowser']();
}

export function CloseBrowser() {
  return window['go']['main']['App']['CloseBrowser']();
}

export function OpenBrowser() {
  return window['go']['main']['App']['OpenBrowser']();
}

export function SetConfig(arg1) {
  return window['go']['main']['App']['SetConfig'](arg1);
}
